### ISSUE TITLE
Consider moving away from Travis CI

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#6993]
With the recent news of the [Travis acquisition](https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/) last month followed by [the significant layoffs last week](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/) I think it's worth discussing options for moving to a different CI provider if the need arises in the near future.

My two personal preferences would be either [GitLab CI](https://about.gitlab.com/solutions/github/) or [CircleCI](https://circleci.com/):

### GitLab CI

[GitLab CI](https://about.gitlab.com/solutions/github/): GitLab CI provides 50k build minutes/month (Note that the page says that the GitHub integration will be moved from the GitLab.com Free plan to the Silver (paid) plan, but my understanding is that open source projects have all Gold features available to them by default, we can get that clarified if we're concerned about it).

Job concurrency is dependent on the availability of the GitLab.com Shared Runners, which can vary somewhat ([there's a public Grafana instance with this kind of info available in realtime if that's interesting to anyone](https://dashboards.gitlab.com/d/000000159/ci?refresh=30m&orgId=1&from=now-3h&to=now)).

You can also use your own runners you host yourself, if that's of any interest.

- [GitLab CI Documentation](https://docs.gitlab.com/ee/ci/)
- [The `.gitlab-ci.yml` config file documentation](https://docs.gitlab.com/ee/ci/yaml/)

### CircleCI

[CircleCI](https://circleci.com/open-source/): CircleCI offers 4 Linux containers with no build limits for open source projects. I used CircleCI a few years ago – in 2015/16ish – and enjoyed it at the time, though I don't have as much recent experience with it.

- [CircleCI Documentation](https://circleci.com/docs/)

---------

Either way, we'd need to get SuiteCRM running in a Docker container to run tests on it (GitLab CI supports non-Docker environments but I'm not familiar with them and I'm not sure if you can do that kind of thing with the Shared Runners provided by GitLab.com).

Both GitLab CI and CircleCI allow you to provide your own containers for running your test suite on. GitLab has a Container Registry you can upload custom images to, I think CircleCI requires you to upload the container to Docker Hub. Both can use container images from Docker Hub.

If you want to see GitLab CI in use on an actual GitHub project, I recently switched to it for [a personal project of mine](https://github.com/connorshea/ContinueFromCheckpoint). See the `.gitlab-ci.yml`, `Dockerfile.ci` (which is the container used by GitLab CI), and any recent pull requests.

Obligatory disclaimer: I'm a former GitLab employee, so I'm obviously biased here. I'm open to any other suggestions people have :)

**Comment by connorshea** [comment]
Here's an example of what the `.gitlab-ci.yml` might look like:

```yml
image: "php:7.2.15-apache-stretch"

services:
  # Probably specify a version for mysql.
  - mysql
  # Add elasticsearch here as well.

variables:
  - INSTANCE_URL: http://localhost
  - DATABASE_DRIVER: MYSQL
  - DATABASE_NAME: automated_tests
  - DATABASE_HOST: localhost
  - DATABASE_USER: automated_tests
  - DATABASE_PASSWORD: automated_tests
  - INSTANCE_ADMIN_USER: admin
  - INSTANCE_ADMIN_PASSWORD: admin1
  - COMPOSER_MEMORY_LIMIT: -1

before_script:
  - php -v
  - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
  - apt-get update -qqy && apt-get install -qqyy google-chrome-stable mysql-client
  # Install composer here (if we're using stretch you can just use apt-get and it should have a pretty recent version)
  - composer install

php-lint:
  script:
    # Put the actual lint command here:
    - php lint

# Use anchors to reuse common configuration options.
# https://docs.gitlab.com/ee/ci/yaml/README.html#anchors
.php:
  script:
    - ./vendor/bin/codecept run install --env travis-ci-hub -f -vvv -d
    # Run API functional tests
    - ./vendor/bin/codecept run tests/api/V8/ -f -vvv -d
    # Run basic acceptance tests
    - ./vendor/bin/codecept run acceptance --env travis-ci-hub -f -vvv -d
  # Save 'var/log/apache2/error.log' and 'suitecrm.log' as artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  artifacts:
    paths:
      - var/log/apache2/error.log
      - suitecrm.log
    expire_in: 2 weeks

php-5.6:
  image: "php:5.6.40-apache-stretch"
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-5.6'
    paths:
      - vendor/
  <<: *php

# I don't see a 7.0.x version of the official php containers on Docker Hub.
# php-7.0:
#   image: "php:7.0.30-apache-stretch"
#   <<: *php

php-7.1:
  image: "php:7.1.26-apache-stretch"
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-7.1'
    paths:
      - vendor/
  <<: *php

php-7.2:
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-7.2'
    paths:
      - vendor/
  <<: *php
```

This _definitely_ won't work, but it's a decent base to start from. I think you'll need to enable some PHP extensions and add a bunch of the commands from the `.travis.yml` that I didn't include here.

-----

For now I'd say ignore custom Dockerfiles and just focus on getting the CI YML working (Docker container building + uploading is slow). But for if/when you want to do it, you'll need a `Dockerfile` for each of the versions of PHP you want to support. Something like this:

```Dockerfile
# Dockerfile for running the application in a CI environment.
# Base image from https://hub.docker.com/_/php/
FROM php:7.2.15-apache-stretch

RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update -qqy && apt-get install -qqyy google-chrome-stable mysql-client
```
