### ISSUE TITLE
Consider using YAML for Vardefs

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7028]
I wanted to propose that the vardef files, including `editviewdefs.php`, `searchdefs.php`, `detailviewdefs.php`, `listviewdefs.php`, etc. be (optionally?) changed to YAML files.

This idea is admittedly kind of crazy, and I don't know how likely it'd be to actually have it adopted, but I figured after the long conversation in Gitter about it I'd open an issue for it.

PHP:

```php
<?php
$searchdefs [$module_name] = 
array (
  'layout' => 
  array (
    'basic_search' => 
    array (
      'name' => 
      array (
        'name' => 'name',
        'default' => true,
        'width' => '10%',
      ),
      'current_user_only' => 
      array (
        'name' => 'current_user_only',
        'label' => 'LBL_CURRENT_USER_FILTER',
        'type' => 'bool',
        'default' => true,
        'width' => '10%',
      ),
      'active' => 
      array (
        'name' => 'active',
        'label' => 'LBL_ACTIVE',
        'type' => 'bool',
        'default' => true,
        'width' => '10%',
      ),
    ),
    'advanced_search' => 
    array (
      'name' => 
      array (
        'name' => 'name',
        'default' => true,
        'width' => '10%',
      ),
      'assigned_user_id' => 
      array (
        'name' => 'assigned_user_id',
        'label' => 'LBL_ASSIGNED_TO',
        'type' => 'enum',
        'function' => 
        array (
          'name' => 'get_user_array',
          'params' => 
          array (
            0 => false,
          ),
        ),
        'default' => true,
        'width' => '10%',
      ),
    ),
  ),
  'templateMeta' => 
  array (
    'maxColumns' => '3',
    'maxColumnsBasic' => '4',
    'widths' => 
    array (
      'label' => '10',
      'field' => '50',
    ),
  ),
);
```

YAML:

```yml
layout:
  basic_search:
    name:
      name: name
      default: true
      width: 10%
    current_user_only:
      name: current_user_only
      label: LBL_CURRENT_USER_FILTER
      type: bool
      default: true
      width: 10%
    active:
      name: active
      label: LBL_ACTIVE
      type: bool
      default: true
      width: 10%
  advanced_search:
    name:
      name: name
      default: true
      width: 10%
    assigned_user_id:
      name: assigned_user_id
      label: LBL_ASSIGNED_TO
      type: enum
      function:
        name: get_user_array
        params:
          - false
      default: true
      width: 10%
    active:
      name: active
      label: LBL_ACTIVE
      type: bool
      default: true
      width: 10%
    location_address_city:
      type: varchar
      label: LBL_LOCATION_ADDRESS_CITY
      width: 10%
      default: true
      name: location_address_city
    location_address_state:
      type: varchar
      label: LBL_LOCATION_ADDRESS_STATE
      width: 10%
      default: true
      name: location_address_state
templateMeta:
  maxColumns: '3'
  maxColumnsBasic: '4'
  widths:
    label: '10'
    field: '50'
```

<details>
<summary>JSON version for funsies</summary>

```json
{
  "layout": {
    "basic_search": {
      "name": {
        "name": "name",
        "default": true,
        "width": "10%"
      },
      "current_user_only": {
        "name": "current_user_only",
        "label": "LBL_CURRENT_USER_FILTER",
        "type": "bool",
        "default": true,
        "width": "10%"
      },
      "active": {
        "name": "active",
        "label": "LBL_ACTIVE",
        "type": "bool",
        "default": true,
        "width": "10%"
      }
    },
    "advanced_search": {
      "name": {
        "name": "name",
        "default": true,
        "width": "10%"
      },
      "assigned_user_id": {
        "name": "assigned_user_id",
        "label": "LBL_ASSIGNED_TO",
        "type": "enum",
        "function": {
          "name": "get_user_array",
          "params": {
            "0": false
          }
        },
        "default": true,
        "width": "10%"
      }
    }
  },
  "templateMeta": {
    "maxColumns": "3",
    "maxColumnsBasic": "4",
    "widths": {
      "label": "10",
      "field": "50"
    }
  }
}
```
</details>

You can generate YAML from a vardefs object with the following script, just replace the comment with your vardefs (after running `composer require symfony/yaml`):

```php
<?php
require 'vendor/autoload.php';
use Symfony\Component\Yaml\Yaml;

$vardefs = array (
  // vardefs here
);

# Dump the PHP object as YAML, with a depth of up to 6 and 2-space indentation.
$yaml = Yaml::dump($vardefs, 6, 2); echo $yaml;
```

So it should be realistically possible to convert between the formats without too much pain (hopefully).

Pros:
- The Vardefs are much easier to read and write
- Less extra syntax
- No need for PHP code in files that are used exclusively for configuration (clear separation of concerns)

Cons:
- Migrating to this format will probably be a huge pain if you're doing anything abnormal here.
- Lots of code to rewrite.
- Maintenance burden, especially if YAML _and_ PHP are supported simultaneously.
- Getting Studio to output consistent YAML when changing a field/module might be difficult (not that it's really consistent currently)
- No way to use variables (do people actually use any sort of dynamic variables in these files?)

Honestly, this _probably_ isn't worth needing to constantly parse/dump the vardefs into/out of YAML when interacting with the CRM. But I thought it was an interesting enough idea to share. Feel free to close this issue if it's unlikely to ever happen :)
